# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "250120d980801ca567c368f72f4697f2"
name = "just-wish-and-shop"
handle = "just-wish-and-shop"
application_url = "https://vintage-promptly-mental-id.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-b560a130.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vintage-promptly-mental-id.trycloudflare.com/auth/callback",
  "https://vintage-promptly-mental-id.trycloudflare.com/auth/shopify/callback",
  "https://vintage-promptly-mental-id.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
